len(a)
Out[5]: 10

for i in len(a):
    print(a[i])

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-ad58209539c2> in <module>()
----> 1 for i in len(a):
      2     print(a[i])
      3 

TypeError: 'int' object is not iterable

clear


a=range(1,10)

for i in range(1,10):
    print (i)
    
1
2
3
4
5
6
7
8
9

a=ramdom
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-10-061c34273a8e> in <module>()
----> 1 a=ramdom

NameError: name 'ramdom' is not defined

a=ramdon
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-11-745bc3cc0208> in <module>()
----> 1 a=ramdon

NameError: name 'ramdon' is not defined

a=random
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-12-705536b636d9> in <module>()
----> 1 a=random

NameError: name 'random' is not defined

random
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-13-61ecbc41cdae> in <module>()
----> 1 random

NameError: name 'random' is not defined

ramdom()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-14-42968b2c7d83> in <module>()
----> 1 ramdom()

NameError: name 'ramdom' is not defined

random()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-15-1f8a42ab0e97> in <module>()
----> 1 random()

NameError: name 'random' is not defined

a=random()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-16-356bf76c3b50> in <module>()
----> 1 a=random()

NameError: name 'random' is not defined

import random

a=random()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-356bf76c3b50> in <module>()
----> 1 a=random()

TypeError: 'module' object is not callable

a=random

random.randint(1,5)
Out[20]: 3

random.randint(1,20)
Out[21]: 11

cadena="anita lava la tina"

for caracter in cadena:
    'print (caracter)
  File "<ipython-input-23-bff0b22757ac>", line 2
    'print (caracter)
                    ^
SyntaxError: EOL while scanning string literal


for caracter in cadena:
    print(caracter)
    
a
n
i
t
a
 
l
a
v
a
 
l
a
 
t
i
n
a

cadenota="esta es una \n\ cadena momkm larga"

print(cadenota)
esta es una 
\ cadena momkm larga

cadenota="esta es una \n cadena momkm larga"

print(cadenota)
esta es una 
 cadena momkm larga

string[1::2]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-29-f442eea2a29c> in <module>()
----> 1 string[1::2]

NameError: name 'string' is not defined

string="a askhdaskjdagshbndjauygdhbajkdah haskaskjdad"

string [1::2]
Out[31]: ' shakdghnjughaka aksja'

>>>

python
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-33-4a69013be9f0> in <module>()
----> 1 python

NameError: name 'python' is not defined





t=True

t=False

print (t)
False

t=True

print (t)
True

math.acos(10)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-39-c0a299ad3ad1> in <module>()
----> 1 math.acos(10)

NameError: name 'math' is not defined

import math

math.acos(10)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-41-c0a299ad3ad1> in <module>()
----> 1 math.acos(10)

ValueError: math domain error

math.random
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-42-e7fa8b55a61d> in <module>()
----> 1 math.random

AttributeError: 'module' object has no attribute 'random'

s.split(c,"")
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-43-e1f7b060ba0f> in <module>()
----> 1 s.split(c,"")

NameError: name 's' is not defined

import s
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-44-0c4264ad1595> in <module>()
----> 1 import s

ImportError: No module named s

s="anita lava la tina"

s.split(c,"")
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-46-e1f7b060ba0f> in <module>()
----> 1 s.split(c,"")

NameError: name 'c' is not defined

s.split()
Out[47]: ['anita', 'lava', 'la', 'tina']

s.split(2,"")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-48-137186b6c2d7> in <module>()
----> 1 s.split(2,"")

TypeError: an integer is required

s.split(meme,"")
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-49-0dec00eb17b7> in <module>()
----> 1 s.split(meme,"")

NameError: name 'meme' is not defined

s.split("hola")
Out[50]: ['anita lava la tina']

s.split(s,"")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-51-11dbde0c9278> in <module>()
----> 1 s.split(s,"")

TypeError: an integer is required

s.split("s","")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-52-5865b6522f79> in <module>()
----> 1 s.split("s","")

TypeError: an integer is required

clear


def nombre:
  File "<ipython-input-54-d415ade54051>", line 1
    def nombre:
              ^
SyntaxError: invalid syntax


def nombre:
  File "<ipython-input-55-d415ade54051>", line 1
    def nombre:
              ^
SyntaxError: invalid syntax


clear


arreglo[[0,0,0][0,0,0][0,0,0]]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-57-738baab31d5a> in <module>()
----> 1 arreglo[[0,0,0][0,0,0][0,0,0]]

NameError: name 'arreglo' is not defined

arreglo = [[0,0,0][0,0,0][0,0,0]]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-58-b718eb394a58> in <module>()
----> 1 arreglo = [[0,0,0][0,0,0][0,0,0]]

TypeError: list indices must be integers, not tuple

arreglo = [[0,0,0],[0,0,0],[0,0,0]]

def filaA(a,b,c):
    return (a*b+c)
def filaB(a,b,c):
    return (a-b+c)
def filaC(a,b,c):
    return (a+b*c)


def columA (a,b,c):
    return(a*b-c)
def columnB (a,b,c):
    return(a+b-c)
def columC(a,b,c):
    return(a+b/c)


arreglo[:1]
Out[62]: [[0, 0, 0]]

arreglo[a,b,c : 1
]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-63-3d0133e60876> in <module>()
----> 1 arreglo[a,b,c : 1
      2 ]

NameError: name 'b' is not defined



filaA(arreglo[:1][0])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-64-6384b2a244b8> in <module>()
----> 1 filaA(arreglo[:1][0])

TypeError: filaA() takes exactly 3 arguments (1 given)

filaA(arreglo[:1][0])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-65-6384b2a244b8> in <module>()
----> 1 filaA(arreglo[:1][0])

TypeError: filaA() takes exactly 3 arguments (1 given)

arreglo = [[3,5,7],[0,0,0],[0,0,0]]

filaA(arreglo[:1][0])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-67-6384b2a244b8> in <module>()
----> 1 filaA(arreglo[:1][0])

TypeError: filaA() takes exactly 3 arguments (1 given)

filaA(arreglo[:1][0][0][0])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-68-84a8db2a97ff> in <module>()
----> 1 filaA(arreglo[:1][0][0][0])

TypeError: 'int' object has no attribute '__getitem__'

filaA(arreglo[:1])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-69-c98282f04433> in <module>()
----> 1 filaA(arreglo[:1])

TypeError: filaA() takes exactly 3 arguments (1 given)

filaA(arreglo[:1])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-70-c98282f04433> in <module>()
----> 1 filaA(arreglo[:1])

TypeError: filaA() takes exactly 3 arguments (1 given)

arreglo[:1]
Out[71]: [[3, 5, 7]]

arreglo[:1][0]
Out[72]: [3, 5, 7]

a,b,c=arreglo[:1][0]

filaA(arreglo[:1][a,b,c])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-74-8b79ad1d6f97> in <module>()
----> 1 filaA(arreglo[:1][a,b,c])

TypeError: list indices must be integers, not tuple

filaA(a,b,c)
Out[75]: 22

arreglo = [[9,7,3],[0,0,0],[0,0,0]]

filaA(a,b,c)
Out[77]: 22

a,b,c=arreglo[:1][0]

filaA(a,b,c)
Out[79]: 66

arreglo = [[9,7,1],[0,0,0],[0,0,0]]

a,b,c=arreglo[:1][0]

filaA(a,b,c)
Out[82]: 64

columA(9,8,5)
Out[83]: 67

columC(8,6,1)
Out[84]: 14

filaA(8,7,3)
Out[85]: 59

filaA(8,7,5)
Out[86]: 61

filaA(8,7,6)
Out[87]: 62

filaA(8,6,9)
Out[88]: 57

columC(9,3,2)
Out[89]: 10

columB(9,3,2)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-90-e6a10a8a04b2> in <module>()
----> 1 columB(9,3,2)

NameError: name 'columB' is not defined

columB(9,3,2)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-91-e6a10a8a04b2> in <module>()
----> 1 columB(9,3,2)

NameError: name 'columB' is not defined

columb(9,3,2)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-92-f0bb8c77dc44> in <module>()
----> 1 columb(9,3,2)

NameError: name 'columb' is not defined

columnB(9,3,2)
Out[93]: 10

s={1,2,3,4,5,6,7,8,9}

A={7,5,4,2}

s|A
Out[96]: {1, 2, 3, 4, 5, 6, 7, 8, 9}

s&A
Out[97]: {2, 4, 5, 7}

s-A
Out[98]: {1, 3, 6, 8, 9}

s^A
Out[99]: {1, 3, 6, 8, 9}
